/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.tesco.billingsystem.gui;

import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EliteBook
 */
public class EmployeeTableT extends javax.swing.JFrame {

    /**
     * Creates new form EmployeeTableT
     */
    public EmployeeTableT() {
        initComponents();
    }
    public EmployeeTableT(List<EmployeeVO> arrayMain){
        initComponents();
        
        //Set column name -->g
        String header[]= new String[]{"IC no","PsWD","Name"};
        DefaultTableModel model = new DefaultTableModel();
        
        model.setColumnIdentifiers(header);
        jTable1.setModel(model);
        
        
        Object rowData[] = new Object[3];
        for(int i=0; i<arrayMain.size();i++){
            rowData[0] = arrayMain.get(i).getIcno();
            rowData[1] = arrayMain.get(i).getPwd();
            rowData[2] = arrayMain.get(i).getName();
            //System.out.println(arrayMain.get(i).getName());
            model.addRow(rowData);
            
             //rowData[1] = arrayMain.get(i).i
               //       rowData[1] = arrayMain.get(i).i
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
